--- #YAML:1.0
name:               CPAN-Testers-ParseReport
version:            0.0.14
abstract:           parse reports to www.cpantesters.org from various sources
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime::Format::Strptime:  0
    File::Path:           0
    Getopt::Long:         0
    HTML::Entities:       0
    IO::Prompt:           0
    List::Util:           0
    LWP::UserAgent:       0
    Pod::Usage:           0
    Statistics::Regression:  0
    Test::More:           0
    Test::Pod:            0
    Time::Local:          0
    XML::LibXML:          0
    XML::LibXML::XPathContext:  0
    YAML::Syck:           0
provides:
    CPAN::Testers::ParseReport:
        file:  lib/CPAN/Testers/ParseReport.pm
        version:  0.0.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.4702
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
repository:         git://repo.or.cz/cpan-testers-parsereport.git
