---
abstract: 'parse reports to www.cpantesters.org from various sources'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Testers-ParseReport
no_index:
  directory:
    - t
    - inc
provides:
  CPAN::Testers::ParseReport:
    file: lib/CPAN/Testers/ParseReport.pm
    version: v0.2.2
requires:
  CPAN::Meta::Converter: 2.110440
  CPAN::Meta::YAML: 0.004
  Class::ISA: 0
  Compress::Zlib: 0
  Config::Perl::V: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  File::Path: 1.08
  File::Spec: 3.34
  Getopt::Long: 0
  HTML::Entities: 0
  Hash::Util: 0
  JSON::PP: 2.27200
  JSON::XS: 0
  LWP::UserAgent: 0
  List::Util: 0
  MIME::QuotedPrint: 3.07
  Parse::CPAN::Meta: 1.4401
  Pod::Usage: 1.33
  Statistics::Regression: 0
  Test::More: 0
  Test::Pod: 0
  Time::Local: 1.11
  version: 0.93
version: v0.2.2
x_repository: git://repo.or.cz/cpan-testers-parsereport.git
